Fix: picker js error in basket on selected date
TypeError: document.getElementById(...) is null
picker_date<.onSelect()
 panier:237
Pikaday.prototype.setDate()
 pikaday.js:788
Pikaday/self._onMouseDown()
 pikaday.js:447